const DATA = window.COURSE_DATA;
const main = document.querySelector('#main');
const glyphs = {compass:'⌖',cells:'◉',skin:'≋',bone:'🦴',muscle:'〽',brain:'🧠',hormone:'✣',heart:'♥',shield:'⬡',lungs:'🫁',digest:'∿',kidney:'◒',dna:'⌬'};

const escapeHTML = (value='') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const formatDate = (iso, opts={month:'short',day:'numeric'}) => new Date(`${iso}T12:00:00`).toLocaleDateString('en-US',opts);
const youtubeSearch = title => `https://www.youtube.com/results?search_query=${encodeURIComponent(title + ' Crash Course')}`;
const topicByCode = code => DATA.systems.flatMap(s=>s.topics).find(t=>t.code===String(code));
const toISODate = value => {
  if(!value) return '';
  if(/^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  const parsed = new Date(value);
  if(Number.isNaN(parsed.valueOf())) return value;
  const y=parsed.getFullYear(),m=String(parsed.getMonth()+1).padStart(2,'0'),d=String(parsed.getDate()).padStart(2,'0');
  return `${y}-${m}-${d}`;
};

function anatomyGraphic(){return `<div class="body-map" aria-hidden="true"><svg viewBox="0 0 260 390" fill="none"><circle cx="130" cy="41" r="28" stroke="#cfe88b" stroke-width="2"/><path d="M110 72C87 82 78 111 80 146L65 242M150 72c23 10 32 39 30 74l15 96M86 126l-7 116m95-116 7 116M101 176l-7 170m65-170 7 170M94 346l-9 26m81-26 9 26M97 79c9 8 19 12 33 12s24-4 33-12" stroke="#cfe88b" stroke-width="2.2" stroke-linecap="round"/><path d="M102 108c10-12 46-12 56 0l-5 62c-11 13-35 13-46 0l-5-62Z" stroke="#cfe88b" opacity=".7"/><path class="pulse" d="M130 122c-12-18-34 1-18 17l18 18 18-18c16-16-6-35-18-17Z" fill="#ef6b49"/><path d="M118 96c-15 2-17 24-8 32M142 96c15 2 17 24 8 32" stroke="#89c9c0" stroke-width="4" stroke-linecap="round"/><path d="M123 26c-10 5-15 21-5 26 4 8 15 8 20 1 11-4 7-24-2-27-3-7-10-7-13 0Z" stroke="#efc34e" stroke-width="3"/><path d="M111 161c-2 15 8 25 19 25s21-10 19-25" stroke="#60a5fa" stroke-width="3"/></svg></div>`}

function renderHome(){
  const systemCards = DATA.systems.map(systemCard).join('');
  main.innerHTML = `<section class="hero"><div class="hero-copy"><p class="overline">Your map of the human body</p><h1>See the body as a <em>connected system.</em></h1><p>Use the daily plan to know where we are. Use the system guides to see where every structure, process, and assignment fits.</p><div class="hero-actions"><a class="button" href="#calendar">Open daily navigator <span>→</span></a><a class="button secondary" href="#systems">Explore body systems</a></div></div><div class="body-graphic">${anatomyGraphic()}</div></section><section class="section today-section" id="today-panel"></section><section class="section systems-section"><div class="section-heading"><div><p class="eyebrow" style="color:var(--teal)">Course atlas</p><h2>Learn by system.</h2></div><p>Every page connects core structures to physiological processes, learning targets, textbook work, and review resources.</p></div><div class="systems-grid">${systemCards}</div></section>`;
  renderToday();
}

function systemCard(s){return `<a class="system-card" href="#system/${s.unit}" style="--unit-color:${s.color}"><div class="system-art"><span class="system-glyph">${glyphs[s.icon]||'◉'}</span><span class="unit-number">${String(s.unit).padStart(2,'0')}</span></div><div class="system-card-copy"><p class="eyebrow">Unit ${s.unit}</p><h3>${escapeHTML(s.name)}</h3><p class="card-kicker">${escapeHTML(s.kicker)}</p><span class="card-link">Explore ${s.topics.length} topics <b>→</b></span></div></a>`}

function mostRelevantDay(){
  const today = new Date(); today.setHours(0,0,0,0);
  const entries=[...DATA.dailyFallback].sort((a,b)=>a.date.localeCompare(b.date));
  return entries.find(x=>new Date(`${x.date}T00:00:00`)>=today) || entries.at(-1);
}

function renderToday(){
  const host=document.querySelector('#today-panel'); if(!host)return;
  const d=mostRelevantDay();
  if(!d){host.innerHTML='<div class="today-card"><div class="today-content"><h2>No daily plan posted yet.</h2><p class="empty-state">Check back when the Navigator is updated.</p></div></div>';return}
  const topic=topicByCode(d.topic);
  host.innerHTML=`<div class="today-card"><div class="today-date"><span class="dow">${formatDate(d.date,{weekday:'long'})}</span><span class="daynum">${formatDate(d.date,{day:'numeric'})}</span><span class="month">${formatDate(d.date,{month:'long'})}</span></div><div class="today-content"><div class="status-row"><span class="topic-badge">${topic?`Topic ${escapeHTML(topic.code)}`:'Daily Plan'}</span><span class="eyebrow">Week ${escapeHTML(d.week)}</span></div><h2>${escapeHTML(topic?.title||'Course work')}</h2><p class="target">${escapeHTML(topic?.target||d.topicText||'Review the plan below.')}</p><div class="today-grid"><div><span>In class</span><p>${escapeHTML(d.classwork||'See classroom instructions.')}</p></div><div><span>Biozone</span><p>${escapeHTML(d.biozone||'No pages assigned.')}</p></div><div><span>After class</span><p>${escapeHTML(d.home||'No homework posted.')}</p></div></div></div></div>`;
}

function parseCSV(text){
  const rows=[];let row=[],field='',quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){field+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);rows.push(row);row=[];field=''}else field+=c}
  if(field||row.length){row.push(field);rows.push(row)}return rows;
}
function normalizeLiveRows(rows){
  const headerIndex=rows.findIndex(r=>r.includes('Week')&&r.includes('Date')); if(headerIndex<0)return [];
  const h=rows[headerIndex]; const col=name=>h.indexOf(name);
  return rows.slice(headerIndex+1).map(r=>({week:r[col('Week')],day:r[col('Day')],date:toISODate(r[col('Date')]),topic:r[col('Topic')],topicText:r[col('Topic Title / I Can…')],classwork:r[col('Class')],biozone:r[col('BIOZONE')],video:r[col('Crash Course / Video')],home:r[col('HOME After Class')],standard:r[col('A&P Target')]})).filter(x=>x.date&&Object.values(x).some(Boolean));
}
async function loadDaily(){
  try{const res=await fetch(DATA.dailyCsv,{cache:'no-store'});if(!res.ok)throw new Error('Unavailable');const live=normalizeLiveRows(parseCSV(await res.text()));if(!live.length)throw new Error('Empty');return {rows:live,live:true}}catch{return {rows:DATA.dailyFallback,live:false}}
}

async function renderCalendar(){
  main.innerHTML=`<section class="navigator-hero"><p class="overline">Daily course map</p><h1>Daily Navigator</h1><p>Learning targets, classwork, BIOZONE pages, videos, and what to complete after class—all in one place.</p></section><section class="navigator-wrap"><div class="navigator-toolbar"><div class="week-controls"><button class="icon-btn" id="prev-week" aria-label="Previous week">←</button><span class="week-label" id="week-label">Loading…</span><button class="icon-btn" id="next-week" aria-label="Next week">→</button></div><span class="sync-status" id="sync-status">Loading published plan</span></div><div class="week-grid" id="week-grid"></div></section>`;
  const {rows,live}=await loadDaily(); let weekIndex=0;
  const weeks=[...new Set(rows.map(x=>String(x.week)))]; const todayIso=new Date().toISOString().slice(0,10);
  const currentRow=rows.find(x=>x.date===todayIso); if(currentRow)weekIndex=Math.max(0,weeks.indexOf(String(currentRow.week))); else {const future=rows.find(x=>x.date>=todayIso);weekIndex=future?weeks.indexOf(String(future.week)):Math.max(0,weeks.length-1)}
  const draw=()=>{const week=weeks[weekIndex];document.querySelector('#week-label').textContent=`Week ${week}`;document.querySelector('#prev-week').disabled=weekIndex===0;document.querySelector('#next-week').disabled=weekIndex===weeks.length-1;document.querySelector('#week-grid').innerHTML=rows.filter(x=>String(x.week)===week).map(dayCard).join('')||'<p>No plans posted for this week.</p>'};
  const status=document.querySelector('#sync-status');status.textContent=live?'Live from the published course sheet':'Showing the framework’s saved schedule';status.classList.toggle('live',live);
  document.querySelector('#prev-week').onclick=()=>{weekIndex=Math.max(0,weekIndex-1);draw()};document.querySelector('#next-week').onclick=()=>{weekIndex=Math.min(weeks.length-1,weekIndex+1);draw()};draw();
}
function dayCard(d){const t=topicByCode(d.topic);const today=d.date===new Date().toISOString().slice(0,10);return `<article class="day-card ${today?'current':''}"><div class="date-line"><span class="weekday">${escapeHTML(d.day||formatDate(d.date,{weekday:'short'}))}</span><span class="date-small">${formatDate(d.date)}</span></div>${t?`<span class="topic-badge">${escapeHTML(t.code)}</span><h3>${escapeHTML(t.title)}</h3><p class="mini-target">${escapeHTML(t.target)}</p>`:'<h3>Course work</h3>'}<div class="day-block"><b>Class</b><p>${escapeHTML(d.classwork||'—')}</p></div><div class="day-block"><b>After class</b><p>${escapeHTML(d.home||'—')}</p></div>${t?`<div class="day-block"><a class="back-link" href="#system/${Number(t.unit.split(' ')[1])}">Open unit guide →</a></div>`:''}</article>`}

function renderSystems(){main.innerHTML=`<section class="navigator-hero"><p class="overline">The complete course</p><h1>Body Systems</h1><p>Begin with foundations, then move through twelve connected units. Each guide includes every framework target, BIOZONE assignment, key vocabulary, and aligned video.</p></section><section class="section"><div class="systems-grid">${DATA.systems.map(systemCard).join('')}</div></section>`}

function renderSystem(id){
  const s=DATA.systems.find(x=>x.unit===Number(id));if(!s)return render404();
  const prev=DATA.systems.find(x=>x.unit===s.unit-1),next=DATA.systems.find(x=>x.unit===s.unit+1);
  main.innerHTML=`<section class="system-hero" style="--unit-color:${s.color}"><div class="breadcrumbs"><a href="#systems">Body Systems</a> / Unit ${s.unit}</div><p class="overline">Unit ${s.unit}</p><h1>${escapeHTML(s.name)}</h1><p>${escapeHTML(s.kicker)}. Use this guide to connect what you must identify with what you must explain.</p><div class="system-stats"><div class="system-stat"><span>${s.topics.length}</span><small>Learning topics</small></div><div class="system-stat"><span>${s.vocabulary.length}</span><small>Key terms</small></div><div class="system-stat"><span>${new Set(s.topics.flatMap(t=>t.videos)).size}</span><small>Video alignments</small></div></div></section><div class="system-layout" style="--unit-color:${s.color}"><section><div class="section-heading"><div><p class="eyebrow" style="color:var(--unit-color)">Learning sequence</p><h2>What you’ll master</h2></div></div><div class="topic-list">${s.topics.map(topicItem).join('')}</div><div class="hero-actions">${prev?`<a class="button secondary" href="#system/${prev.unit}">← ${escapeHTML(prev.name)}</a>`:''}${next?`<a class="button" href="#system/${next.unit}">${escapeHTML(next.name)} →</a>`:''}</div></section><aside class="side-panel"><div class="vocab-card"><p class="eyebrow" style="color:var(--lime)">Language of the system</p><h2>Key vocabulary</h2><p>Be able to identify these terms in context and use them to explain a process.</p><div class="vocab-list">${s.vocabulary.map(v=>`<span class="vocab-chip">${escapeHTML(v)}</span>`).join('')}</div></div><div class="connections-card"><p class="eyebrow" style="color:var(--unit-color)">Keep connecting</p><h2>Structure → function</h2><p>For every structure, ask: What feature allows it to do its job? What would happen if that feature changed?</p><a class="back-link" href="#calendar">View this week’s work →</a></div></aside></div>`;
}
function topicItem(t){const videos=t.videos.map(v=>`<a class="resource-pill" href="${youtubeSearch(v)}" target="_blank" rel="noopener">▶ ${escapeHTML(v.replace('Crash Course A&P ','CC A&P '))}</a>`).join('');return `<details class="topic-item" id="topic-${t.code}"><summary><span class="topic-code">${escapeHTML(t.code)}</span><h3>${escapeHTML(t.title)}</h3></summary><div class="topic-body"><p class="i-can">${escapeHTML(t.target)}</p><div class="topic-meta"><div class="meta-box"><span>Performance target</span><p>${escapeHTML(t.detail)}</p></div><div class="meta-box"><span>BIOZONE 3rd Edition</span><p>Activities ${escapeHTML(t.biozoneActivities)} · Pages ${escapeHTML(t.biozonePages)}</p></div><div class="meta-box"><span>Course target</span><p>${escapeHTML(t.standard)}</p></div><div class="meta-box"><span>Digital support</span><p>${escapeHTML(t.hubSupport||'Check the course resources.')}</p></div></div><div class="resource-links"><a class="resource-pill" href="${DATA.biozoneHub}" target="_blank" rel="noopener">BIOZONE Resource Hub ↗</a>${videos||`<a class="resource-pill" href="${DATA.crashCourseHub}" target="_blank" rel="noopener">Crash Course A&P hub ↗</a>`}</div></div></details>`}

function renderResources(){main.innerHTML=`<section class="resources-hero"><p class="overline">Study with purpose</p><h1>Course Resources</h1><p>Use each resource for a different job: learn the core sequence, visualize difficult processes, then retrieve and explain from memory.</p></section><section class="resources-grid"><article class="resource-card"><span class="resource-icon">📗</span><h2>BIOZONE Hub</h2><p>Online support paired with Anatomy &amp; Physiology, 3rd Edition activities. Your system guides show the relevant activity and page range.</p><a href="${DATA.biozoneHub}" target="_blank" rel="noopener">Open resource hub ↗</a></article><article class="resource-card"><span class="resource-icon">▶</span><h2>Crash Course A&amp;P</h2><p>Short, concept-rich review videos. Each unit guide links to searches for its specifically aligned episodes.</p><a href="${DATA.crashCourseHub}" target="_blank" rel="noopener">Browse the official series ↗</a></article><article class="resource-card"><span class="resource-icon">🧭</span><h2>Daily Navigator</h2><p>Your source for the day’s target, class task, textbook pages, and after-class work. Check it before class and again before leaving.</p><a href="#calendar">Open daily plan →</a></article><article class="resource-card"><span class="resource-icon">🧠</span><h2>Retrieval Practice</h2><p>Cover the guide and reconstruct a pathway, label a structure, or explain a feedback loop without notes. Check only after committing an answer.</p><a href="#systems">Choose a system →</a></article><article class="resource-card"><span class="resource-icon">🔬</span><h2>Structure–Function Lens</h2><p>Use the same thinking routine everywhere: identify the structure, name its distinctive feature, connect that feature to a function, and predict disruption.</p><a href="#system/0">Start with foundations →</a></article><article class="resource-card"><span class="resource-icon">🔗</span><h2>System Connections</h2><p>No system works alone. Trace how nervous and endocrine control coordinates transport, exchange, defense, movement, and homeostasis.</p><a href="#systems">See the course atlas →</a></article></section>`}
function render404(){main.innerHTML='<section class="error-page"><h1>404</h1><p>That body system was not found.</p><a class="back-link" href="#systems">Return to the course atlas</a></section>'}

function route(){const route=location.hash.slice(1)||'today';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',route.startsWith(a.dataset.nav)||(route.startsWith('system/')&&a.dataset.nav==='systems')));if(route==='today')renderHome();else if(route==='calendar')renderCalendar();else if(route==='systems')renderSystems();else if(route==='resources')renderResources();else if(route.startsWith('system/'))renderSystem(route.split('/')[1]);else render404();window.scrollTo(0,0)}

const dialog=document.querySelector('#search-dialog'),search=document.querySelector('#global-search'),results=document.querySelector('#search-results');
document.querySelector('#open-search').onclick=()=>{dialog.showModal();setTimeout(()=>search.focus(),50)};
search.oninput=()=>{const q=search.value.trim().toLowerCase();if(q.length<2){results.innerHTML='<p class="empty-state">Type at least two letters to search the full course.</p>';return}const found=[];DATA.systems.forEach(s=>{s.topics.forEach(t=>{if([t.title,t.target,t.detail,t.standard,...s.vocabulary].join(' ').toLowerCase().includes(q))found.push({s,t})})});results.innerHTML=found.slice(0,30).map(({s,t})=>`<a class="search-result" href="#system/${s.unit}" data-close><b>${escapeHTML(t.code)} · ${escapeHTML(t.title)}</b><p>Unit ${s.unit}: ${escapeHTML(s.name)}</p></a>`).join('')||'<p class="empty-state">No matching course topics.</p>';results.querySelectorAll('[data-close]').forEach(a=>a.onclick=()=>dialog.close())};
document.querySelector('.menu-toggle').onclick=e=>{const nav=document.querySelector('#site-nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.querySelector('#site-nav').classList.remove('open'));
window.addEventListener('hashchange',route);route();
